version: '3'
services:
    app:
        image: webservice
        ports:
            - 8081
        environment:
            - SERVICE_PORTS=8081
        deploy:
            replicas: 2
            update_config:
                parallelism: 5
                delay: 10s
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        networks:
            - web
    proxy:
        image: dockercloud/haproxy
        depends_on:
            - webservice
        environment:
            - BALANCE=roundrobin
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:80
        networks:
            - web
        deploy:
            placement:
                constraints: [node.role == manager]
networks:
    web:
        driver: overlay